class App.Routers.AdminRouter extends Backbone.Router
    routes:
      '': 'index',
      'about': 'about',
      'contact': 'contact'
    initialize: ->
      window.headerView = new App.Views.Header()
      window.footerView = new App.Views.Footer()
      window.adminSideView = new App.Views.AdminSide()
      window.adminChatView = new App.Views.AdminChat()
      $('#multi').select2({
          theme: "bootstrap"
      });
      $('#text-editor').wysihtml5();
      $('.input-append.date').datepicker
        autoclose: true
        todayHighlight: true
      $('#dp5').datepicker()
      $('#sandbox-advance').datepicker
        format: 'dd/mm/yyyy'
        startView: 1
        daysOfWeekDisabled: '3,4'
        autoclose: true
        todayHighlight: true
      return

      # ---
      # generated by js2coffee 2.1.0
    # about: ->
    #   window.aboutView = new App.Views.About()
    # index: ->
    #   window.indexView = new App.Views.Home()
    # contact: ->
    #   window.contactView = new App.Views.Contact()