class App.Routers.AdminRouter extends Backbone.Router
    routes:
      '': 'index',
      'about': 'about',
      'contact': 'contact'
    initialize: ->
      window.headerView = new App.Views.Header()
      window.footerView = new App.Views.Footer()
      window.adminSideView = new App.Views.AdminSide()
      window.adminChatView = new App.Views.AdminChat()
      $('[data-init-plugin="select2"]').select2(minimumResultsForSearch: if $(this).attr('data-disable-search') == 'true' then -1 else 1).on 'select2-opening', ->
            $.fn.scrollbar and $('.select2-results').scrollbar(ignoreMobile: false)
            return
      $('#text-editor').wysihtml5();
      return

      # ---
      # generated by js2coffee 2.1.0
    # about: ->
    #   window.aboutView = new App.Views.About()
    # index: ->
    #   window.indexView = new App.Views.Home()
    # contact: ->
    #   window.contactView = new App.Views.Contact()